# Generated by Django 5.0.1 on 2024-02-02 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolWeb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='img',
            field=models.ImageField(default='image/IMG3.JPG', upload_to='images/'),
        ),
    ]
