# Generated by Django 5.0.1 on 2024-02-02 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolWeb', '0002_home_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='img',
            new_name='Image',
        ),
    ]
