# Generated by Django 5.0.1 on 2024-02-09 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolWeb', '0003_rename_img_home_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='Login',
            new_name='Login_home',
        ),
    ]
